---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cliffano/command-docker-action@v1.0.0
        with:
          command: 'make deps-extra-apt ci'
          image: cliffano/studio:1.5.0
          shell: bash
